---
global:
  smtp_smarthost: "localhost:587"
  smtp_from: "alertmanager@localhost"
  resolve_timeout: 5m

templates:
  - "/etc/alertmanager/*.tmpl"

route:
  group_by: ["alertname", "cluster", "service"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: "default"

receivers:
  - name: "default"
