---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "main"
    replica: "01"

# Send metrics to ClickHouse via remote write
# Temporarily disabled until ClickHouse remote write endpoint is properly configured
# remote_write:
#   - url: "http://clickhouse:9090/api/v1/write"
#     queue_config:
#       capacity: 10000
#       batch_send_deadline: 5s
#       max_samples_per_send: 1000
#       min_backoff: 100ms
#       max_backoff: 30s
#     metadata_config:
#       send: true
#       send_interval: 30s

# Alerting rules
rule_files:
  - "rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Scrape targets
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s

  - job_name: "clickhouse"
    static_configs:
      - targets: ["clickhouse:8123"]
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: "hyperdx"
    static_configs:
      - targets: ["hyperdx-ui:3000"]
    metrics_path: /api/metrics
    scrape_interval: 60s

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    metrics_path: /metrics
    scrape_interval: 60s
